image: node:6.11.2
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
            - pip
          script:
            - apt-get update
            - python --version
            - apt-get -y install python-dev
            - apt-get -y install python-pip
            - pip install awscli
            - pip --help
            - aws --version
            - yarn install
            - yarn build
            - aws --region ap-southeast-2 s3 sync build/ s3://static-react-talk --cache-control "public, max-age=14400" --delete
